version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.11

commands:
  build_app:
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - build

executors:
  node-machine:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.15.0-stretch

  python-machine:
    working_directory: ~/repo
    docker:
      - image: circleci/python:2.7-jessie

jobs:
  checkout_code:
    executor: node-machine
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  bundle_yarn:
    executor: node-machine
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - build-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - build-cache-{{ checksum "yarn.lock" }}-
            - build-cache-
      - run: yarn install --frozen-lockfile
      - run: mkdir -p ~/repo/.Cypress
      - run: if [ -r ~/.cache/Cypress ]; then rm -rf ~/repo/.Cypress/*; mv ~/.cache/Cypress ~/repo/.Cypress; fi
      - save_cache:
          key: build-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/repo/node_modules
            - ~/repo/.Cypress
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules
            - .Cypress

  run_end_to_end_tests:
    working_directory: ~/repo
    docker:
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Running E2E tests
          command: CYPRESS_CACHE_FOLDER=~/repo/.Cypress/Cypress yarn cypress:run
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
